iissnan/hexo-theme-next

_config.yml, layout/_partials/head.swig, layout/_partials/header.swig
Fix https://github.com/iissnan/hexo-theme-next/issues/12
=> Fix rss link in <head>

_config.yml, layout/_partials/header.swig
感谢作者的next主题，比较粗暴的直接在menu上增加了一个站内搜索框，更多的只是提个想法，希望能在下个版本中加入呢***第一次提交pull request好激动~***  
[在线预览](http://lizhuolun.com) | http://lizhuolun.com
在站点的配置文件中增加
```
swiftype_key: yourswiftypekey
```
* 在官网后台控制面板中选择install，可看到自己的swiftype_key
* 在这里默认使用了Swiftype的overplay样式，感觉和主题蛮搭的,也需要在Swiftype的官网后台设置一下，将样式改为overplay。
**勾选overplay样式后保存即可，无需添加代码**
> Swiftype比什么百度站内搜索和google站内搜索好看多了，没有那么强的割裂感。
=> 增加Swiftype站内搜索

layout/_partials/header.swig, source/css/_section/header.styl
这个PR修复了以下问题：
* 官网的代码已经更新到v2版本了，原来的代码已经失效了
* 官网提供的搜索框的class样式为`st-default-search-inupt`，而不是原来的`st-search-input`
* 默认的搜索栏位置有点偏下，加了`float:left`后效果稍微好一些(Mist上的效果不变)，如下图：
* 调整了搜索框在移动设备上的样式，移动设备上搜索框会变大，其他菜单项会换行，如下图：
另外，WIKI里swiftype的配置也已经过期了，官网中设置时最重要的是三四两步。
* 搜索框设置和搜索结果样式设置
* 搜索框设置中直接选择“我已经有搜索框了”，而不是“我需要一个搜索框”，因为代码中已经包含搜索框
* 搜索结果样式设置中对应原来的Overlay的设置
=> 修复Swiftype搜索

README.en.md
Added documentation of default language, Duoshuo and Disqus comments,
integration with Social Media as well as how to use an avatar.
I tried translating bits and pieces of the chinese readme as well as testing it myself.
In the README.md I did not find any info on how to set an avatar, so you might want to add it there, too.
=> Extended english documentation (README.en.md)

source/css/_common/_core/base.styl
出现空白的原因是如果文章中出现了过长的url，会导致a标签的宽度溢出父元素，撑开整个页面，导致右侧出现空白。
这可能会导致某些手机浏览器拖动代码块时，代码块无法横向滚动，而是整张页面横向滚动的bug
=> 修复next移动端右侧出现空白的问题

source/js/fancy-box.js
fancybox生成链接
标签需要携带图片的title，这样才能保证在页面fancy box中显示title内容
=> 保证图片的title可以在fancy box中显示

layout/_layout.swig, layout/_partials/search/tinysou.swig, layout/_scripts/tinysou.swig
启用tinysou时有**很大概率**会使动画失效，控制台报错
```
$(...).velocity is not a function
```
把相关js代码移动到页面底部可以解决这个问题。
=> 修复tinysou代码破坏动画效果

_config.yml, layout/_scripts/comments/duoshuo.swig, source/js/hook-duoshuo.js
完善这个[PR](https://github.com/iissnan/hexo-theme-next/pull/286#issuecomment-132862802)#286 ，一个小功能，自定义博主在UA显示页面里的昵称。
---
使用方法:
------
如果喜欢默认的`博主`字段，则不需要对配置做任何更改，按照[这里](https://github.com/iissnan/hexo-theme-next/pull/286#issuecomment-121923123)的方式配置即可。
如果想将其更改为其余字段，譬如`ROOT`、`Admin`等，需要在主题配置的`duoshuo_info`字段下，将` #admin_nickname: ROOT`的注释取消，然后将`ROOT`改成你想要的任何名字即可
---
预览效果：
-----
**默认：**
**自定义后:**
=> 添加博主在ua显示页面里的昵称自定义功能

layout/_partials/head.swig
RT,这样对于有自定义keywords需求的使用者来说更灵活
=> 如果文章front-matter里有keywords属性，则使用页面的keywords，而不是直接使用tags

source/js/fancy-box.js
Please view demo [here](http://fancyapps.com/fancybox/#examples). In gallery mode, the box can be navigated via mouse clicking on the image or pressing arrow key.
=> Enable Fancybox image gallery

source/css/_custom/custom.styl, source/js/fancy-box.js
图片标题减小了字号; 标题字体样式由斜体更改为粗体; 为class="full-image"的图片添加标题样式.
更改为只有设置了title的图片才显示标题, 不设置则不显示.
图片标题样式可见：http://blog.mrx.one
=> 优化图片标题样式; 更改是否显示图片标题的判断条件. - master branch

source/css/_common/_component/posts.styl, source/js/fancy-box.js
之前那次PR被覆盖掉了，重新提交下。
更新内容：
图片标题减小了字号; 标题字体样式由斜体更改为粗体; 为class="full-image"的图片添加标题样式.
更改为只有设置了title的图片才显示标题, 不设置则不显示.
图片标题样式可见：http://blog.mrx.one
=> 优化图片标题样式; 更改是否显示图片标题的判断条件.

layout/_partials/head.swig
由于360字体库不支持HTTPS，网站开启HTTPS后无法加载字体，所以更换为中科大的字体库，支持HTTPS。
=> 使用中科大字体库替换360字体库

layout/_scripts/comments/duoshuo.swig, source/js/hook-duoshuo.js
修复当用户使用自己托管的多说脚本时，因找不到`http://static.duoshuo.com/embed.js`而报`Uncaught TypeError: Cannot set property 'onload' of undefined`的BUG。
错误截图：
=>  使用id获取多说script对象

layout/_scripts/mathjax.swig
mathjax的js加载速度比较慢，一个js文件的加载都超过1s。改为七牛静态文件cdn，mathjax js加载速度快些。
但是：最新版的MathJax已经是2.5版本。七牛cdn上最新的2.4版本。
=> change mathjax cdn to staticfile.org cdn

source/css/_common/_component/posts-expand.styl
I found that the next theme do not align the image center.
And based on what I can found on css, when `.fancy-box` is applied to the image, usually we want that image to align center:
```css
.posts-expand .fancybox img { margin: 0 auto; }
```
But the fact is that, there is another rule which also meet the `img` element, which overwrite this rule:
```css
.posts-expand .post-body img { margin: 0 }
```
The second on is before the fancybox, so the img cannot align center.
So let's fix it.
=> Fix the issue of image not align center

languages/en.yml, source/css/_common/components/sidebar/site-state.styl
Issues：
1. missing the "visitors" under english language for `visitor counter` item, right now it will use chinese string under english language config, so add it.
2. the site state items, such as `tags`, `categories` and `posts`, when under english language, because the `categories` word is long, so the div with `site-state-item` is wrapped. So let's fix it.
=> add missing loc string and fix site state item wrap issue under en

source/css/_common/_section/header.styl
手机浏览器中触发导航菜单后，页面会被缩小一点点，并且整体可以左右滑动，做以下修改后bug被fix：
contribute path: tongsucn@d81a524
source/css/_common/_section/header.styl
=> Fix issue #499

source/css/_common/_component/posts-expand.styl, source/css/_variables/default.styl
The default scheme has considerable white space above and below the post separator on index pages. This change makes the white space variable by creating two new variables in `/source/css/_variables/default.styl` and using them in `/source/css/_common/_component/posts-expand.styl` to allow theme users to adjust white space easily.
=> Variable white space above/below post separator

source/js/src/hook-duoshuo.js
userId是string，CONFIG.duoshuo.userId是number，所以不用严格比较
=> 修复多说评论不显示admin_nickname名称问题

source/css/_common/_component/posts-expand.styl
See https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Advanced-Configuration#automatic-headline-ids
hexo-renderer-markdown can add permalinks to headings. However, they are
prepended to the heading and styled like a regular link, which doesn't look
that good. This pull request moves it to the right, hides it when not hovering the
heading, and tones it down until the actual anchor is hovered.
You can preview what it looks like now over here: http://vincenttunru.com/Error-Error-while-waiting-for-Protractor-to-sync-with-the-page/#how-to-solve-it (hover over the heading)
=> Style hexo-renderer-markdown-it's automatic headline ID's

source/css/_common/components/post/post-expand.styl
为什么在`source/css/_common/_component/`下有个同名文件呢？之前的修改只修改一处无效。
=> Fix issue #606

source/css/_common/components/pages/archive.styl
Pisces 设置了一个白色背景，导致时间轴被覆盖。给其父元素增加一个层级。
=> Fix issue #609

source/css/_common/scaffolding/helpers.styl
已经在utils.js中使用embeddedVideoTransformer方法指定了内嵌视频的样式，删除helpers.styl中重复的样式，修复因套用两层position:relative导致的视频显示异常。
=> Fix issue #616

_config.yml, layout/_partials/share/add-this.swig, layout/post.swig
**添加AddThis理由：**
1. 更为清爽的设计风格（个人认为好于JiaThis）
2. 除了Facebook、Twitter、Google+、Linkedin等海外常用的分享外，还包括微博在内的上百分享选择
3. Mobile Friendly
4. Freemium
**注册AddThis方法**
1. 在网站[AddThis](https://www.addthis.com/)上注册账号。可以使用Google/Facebook/Twitter账号进行第三方登陆。
2. 从下面菜单获得AddThis id：`More.. --> General --> ID`。具体ID获得方式可以[参考截图](http://i.imgur.com/HN2Dcwb.png)。
3. 在主题`_config.yml`中，把`#Share`下的
`#add_this_id`
取消注释，改为
`add_this_id: put_your_add_this_id_here`
**参考网站**
[我的博客](http://hackjustu.ninja/)加入了AddThis分享功能。点击进入任何一个post，把鼠标放到屏幕左侧即滑出分享按钮（按钮滑出的位置可以在AddThis网站调整）。当屏幕缩小到移动设备大小时，或者在手机上看时，按钮显示在屏幕下方。
我使用的主题版本是去年十月左右fork出去的，所以看起来有点不同。我用最新的主题测试过，没有问题：）
=> 添加AddThis社交分享功能

layout/_macro/post.swig, layout/_macro/reward.swig
越来越多的平台（微信公众平台，新浪微博，简书，百度打赏等）支持打赏功能，付费阅读时代越来越近，特此增加了打赏功能，支持微信打赏和支付宝打赏。只需要_config.xml中填入微信和支付宝收款二维码即可开启该功能。
未点击效果
鼠标悬浮效果
点击之后效果
=> Add wechat and alipay reward for post

layout/_layout.swig, layout/_partials/header.swig, layout/_partials/search.swig, layout/_partials/search/localsearch.swig, layout/_scripts/third-party/localsearch.swig, source/css/_common/components/third-party/localsearch.styl, source/css/_common/components/third-party/third-party.styl, source/css/_common/scaffolding/helpers.styl, source/css/_schemes/Mist/index.styl, source/css/_schemes/Muse/_search.styl, source/css/_schemes/Pisces/_brand.styl
!dea and core codes are from [Joseph Pan](http://hahack.com/codes/local-search-engine-for-hexo/).
see [Wiki](https://github.com/iissnan/hexo-theme-next/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2).
=> new feature: local search

layout/_partials/head.swig
```
{% set theme.rss = config.root + config.feed.path %}
```
then
```
url_for(theme.rss)
```
results in doubling path prefix.
=> Fix rss feed url

source/css/_common/scaffolding/tables.styl
1. Force table size by fix the layout.
2. Force word break even there is no available breakpoints.
=> Fix overflow of table content when in mobile view

source/css/_schemes/Pisces/_sidebar.styl
当使用主题 Pisces，并且 site-state-item 不足三个、只有一个或两个 site-state-item 的时候，site-state 是左对齐的，很不好看没有平衡感，将 site-state 修改为居中对齐
=> site-state center align in sidebar when theme is Pisces

_config.yml, layout/_macro/post.swig, layout/_macro/wechat-subscriber.swig
=> add wechat subscriber

layout/_macro/sidebar.swig
修复当未设置友情连接时链接区域会显示的问题。
Before:
After:
=> Fix friendly links

layout/_macro/sidebar.swig
Add icon for friendly link title, see [友情链接](http://theme-next.iissnan.com/theme-settings.html#blogroll), add a new item `links_icon`
```
links_title: Links
links_icon: heartbeat
links:
MacTalk: http://macshuo.com/
Title: http://example.com/
```
The result can be seen on http://consen.github.io and http://mayliar.github.io
=> add icon for friendly link title.

source/js/src/post-details.js
Earlier today I ran the `gulp` command in my project and got this error regarding a missing semi-colon. As per gulp's suggestion, I then went into `source/js/post-detail.js` and saw that there was in fact a missing semi colon on line [48](https://github.com/iissnan/hexo-theme-next/blob/master/source/js/src/post-details.js#L45) so I took the proper steps (added the semi-color), and after that gulp ran to success. 
Below, you can see the minor change I made. 
Also, awesome theme man! I really enjoy using it... thank you 😄
=> minor bug in JS code

layout/_partials/head.swig, layout/_partials/head/custom-head.swig
用户可以自行在head中加入信息。这样做有两个好处：
1. 灵活性，比如百度统计之类的功能即便主题不支持也可以自己添加
2. 易于更新，避免了用户修改 `head.swig` 之后更新主题时出现冲突
=> support custom head

_config.yml, layout/_scripts/third-party/mathjax.swig
原始代码中若开启`mathjax`选项，则所有页面都会加载mathjax。如果100篇博文里只有10篇有公式，那么对于另外90篇博文来说，加载mathjax就太浪费了。此PR的目的是实现仅当需要时再加载mathjax。
改动只有两处：
1. 加了配置参数 `per_page`，默认值为`false`
2. 加了判断条件 `{% if not theme.mathjax.per_page or (page.total or page.mathjax)%}` （其他行只是修改了代码缩进）
最终的结果是：
1. 若`theme.mathjax.enable==false`，则所有页面都不加载mathjax
2. 若`theme.mathjax.enable==true`，且 `theme.mathjax.per_page==false`，则所有页面都加载mathjax。由于`theme.mathjax.per_page`默认值为`false`，所以增加这个参数不会造成兼容性问题，不介意所有页面都加载mathjax的只要不修改这个参数就可以了
3. 若`theme.mathjax.enable==true`，且 `theme.mathjax.per_page==true`，则意味着会按需加载mathjax。此时需要在每个有公式的博文的front-matter中加上`mathjax: true`。新增的条件语句的后半部分的作用是仅在index页以及`mathjax: true`的页面加载mathjax。
这里的一个小trick是，使用 `page.total`来判断当前页面是否是index。对于index页面，`page.total`是当前页面的总post数目，相当于true，对于post页面，`page.total`是未定义的，相当于false。
=> load mathjax only when mathjax is needed

layout/_scripts/third-party/comments/disqus.swig
Previously if you had a single quote in your post title a javascript error would prevent the page from functioning correctly. With this functionality we will double quote the `post.title` in the inject javascript and use the builtin swig filter `addslashes` to escape characters that need to be escaped.
=> double quote and use addslashes on disqus title

_config.yml, layout/_partials/comments.swig, layout/_scripts/third-party/analytics/facebook-sdk.swig
In this commit:
1. Upgrade Facebook SDK from v2.5 to v2.6 (2016/04/12)
2. Support Facebook Comments Plugin
You could find the demonstration via [this link](https://hydai.co/2016/05/22/helloworld/?fb_comment_id=1198213520198318_1198218393531164#fe8ed19e0dfb8a).
And the following is the screenshot from my demonstration page:
=> Support Facebook Comments Plugin.

source/js/src/utils.js
wrapImageWithFancyBox 这个功能除了要排除 .group-picture 中的 img 以外，还应该排除 .post-gallery 中的 img。因为 .post-gallery 中的 img 已经包围 fancybox，并且拥有相同的 rel 属性，如果再次应用的话，虽然不会再套一层链接，但 rel 属性会变成跟相册图片之外的图片一样的 "group"，这样 fancybox 中的下一张和上一张会浏览到相册以外的无关图片。现已修复，请 merge。
=> gallery posts 中的图片不应该被再次 fancybox 化

layout/_layout.swig
在 front-matter 中指定 `lang: <lang_code>` 或 ` language: <lang_code>` 对于 hexo 来说是有作用的，hexo 会应用主题中相应的语言文件生成对应语言的页面，如果 front-matter 中没有特殊指定，则采用站点配置文件中所设定的语言，从而使特定页面的语言不同于整站语言。而 next 中，页面的 lang 属性被强制设定为站点配置文件中指定的语言，对于多语言博客来说，会产生页面实际语言与 lang 属性中描述的语言不一致的情况。虽然多语言博客需求可能不大，但代码改动也不大，建议 merge。
=> make value of lang attr responsive

layout/_partials/footer.swig
before: http://hexo.io  
after: https://hexo.io
=> Change footer's Hexo URL from http to https

_config.yml, layout/_macro/post.swig, layout/_partials/comments.swig, layout/_scripts/third-party/comments.swig, layout/_scripts/third-party/comments/hypercomments.swig
Add support for [Hypercomments](https://www.hypercomments.com/) system instead of [Disqus](https://disqus.com/).
- Anonymous comments.
- Inline comments like Duoshuo (u can select any text and make comment for this text).
- Share selected text with title in social (Facebook, Twitter, VK).
- Copy quotes (when u copy selected text from site it will appear at quotes tab in comments).
- Stereocommets (mode with moderators’ avatars/mode with company logo)
- Categories (will help users to add a comment to the appropriate section e.g.'Сriticism', 'Reference', 'Request' etc.).
- Emoji in comments. :relieved:
- Real-time online post views.
- Real-time moderation.
U can see and test live demo of hypercomments [here](https://almostover.ru/2016-10/add-hypercomments-to-hexo-theme-next/).
=> Add Hypercomments system.

gulpfile.coffee, layout/_partials/head.swig
今天博客突然变白屏看不到文章了，检查发现多说js错误导致后面的fancybox出错，文章元素被设为opacity:0导致的白屏。
多说的模板head.swig文件里
`duoshuo: {
userId: {{ theme.duoshuo_info.user_id | default() }},
author: '{{ theme.duoshuo_info.admin_nickname | default(__('author'))}}'
}`
这里的userId没有加引号，一些情况下没有被正确当成字符串处理，浏览器会报对象未定义的错误，加上引号后就都不会出错了,
没有引号时浏览器会报错，报错图片
您看下是不是存在这个问题
=> duoshuo  Head.swig template configuration is missing symbol problem

layout/_partials/share/add-this.swig
The reason is due to lack the style of the button. Now it works.
Add the document need to update since the user need to visit AddThis, under the "Tools" menu, select the according style, just pick the "inline share buttons", that's ok.
=> Update add-this.swig, fix a not-shown problem

layout/_scripts/third-party/comments/duoshuo.swig, layout/_scripts/third-party/localsearch.swig, source/css/_common/components/third-party/localsearch.styl
1、美化localsearch弹窗显示
2、修复localsearch算法小bug
bug描述：
``isMatch``变量默认为``true`` (localsearch.swig 46行)，那么当 search.xml 中出现有标题但无内容的条目时，算法会绕过字符串匹配过程，这将导致该条目会永远显示在搜索结果中，不论是否匹配。
当 hexo-generator-search 插件``field: all``时生成的 categories 和 tags 页面内容为空，所以此时无论输入什么内容，搜索结果中都会显示这两个页面。
bug修复之前：
bug修复之后：
修改之后的 localsearch 效果演示[www.wuxubj.cn](http://www.wuxubj.cn)
=> improvement of localsearch

source/css/_common/components/highlight/diff.styl, source/css/_common/components/highlight/highlight.styl, source/css/_schemes/Pisces/_layout.styl, source/css/_variables/base.styl
1. Add support diff highlight style (#1079).
2. Add border radius to code blocks.
3. Tomorrow theme on single code blocks.
[Demo](https://almostover.ru/2016-01/hexo-next-diff-highlight-test/).
---
---
---
=> Fixes in CSS styles of code blocks.

layout/_layout.swig, layout/_macro/post-collapse.swig, layout/_macro/post.swig, layout/_macro/sidebar.swig, scripts/tags/note.js, source/css/_common/components/highlight/highlight.styl, source/css/_common/components/tags/note.styl, source/css/_common/components/tags/tags.styl
{% note class %}
Content (md partial supported)
{% endnote %}
Class: default, primary, success, info, warning, danger
P.S. In live demo i change style on my own custom styles.
=> Fixes and improvements.

_config.yml, languages/en.yml, languages/zh-Hans.yml, layout/_layout.swig, layout/_scripts/third-party/schedule.swig, layout/schedule.swig, source/css/_common/components/pages/pages.styl, source/css/_common/components/pages/schedule.styl
这是一个可以实时显示一定时间范围内的日程的插件（比如4小时前~24小时后）。
我写了 `layout/_scripts/third-party/schedule.swig` 这个文件，可以在前端读取一个**公开**的 Google Calendar，并将一定时间范围内的日程展示在 schedule 页面上。只需要有 Google Calendar 的 api_key 和对应 calendar 的 calendar_id 即可。获取的数据暂时存储在 cal_data 这个变量中，merge 到 master 的时候可以去掉。
我没有做美化完全就是个骨架，我相信你对主题更了解，如果你喜欢，你能帮我完成吗？
相关的 API Doc：https://developers.google.com/google-apps/calendar/v3/reference/events/list
获取 API_KEY：https://console.developers.google.com/
如何设置公开的 Google 日历：https://support.google.com/calendar/answer/37083?hl=en
目前的效果
http://blog.zealoft.com/schedule/
TODO:
=> 加入 Google Calendar 支持，并完成了一个包含前端逻辑的日程页面

_config.yml, layout/_macro/post.swig, layout/_partials/footer.swig
1. Add: meta descriptions on posts
2. Add: noindex for some search engines like Yandex.
Addition to #1175.
Many peoples not like footer copyright. And no matter, what copyright is this; this is add  external links to all pages in your blog — this good for developers, but bad for bloggers.
So, for now u may choose: set footer `copyright` to `true` or to `false`.
=> Fixes and enhancements. [4]

_config.yml, layout/_scripts/third-party/analytics.swig, layout/_scripts/third-party/analytics/application-insights.swig
Add Application Insights analytics support. Application Insights for web pages allows to get timings of page loads and AJAX calls, counts and details of browser exceptions and AJAX failures, as well as users and session counts. All these can be segmented by page, client OS and browser version, geo location, and other dimensions. You can set alerts on failure counts or slow page loading. And by inserting trace calls in your JavaScript code, you can track how the different features of your web page application are used. More details can be found on [offical page](https://azure.microsoft.com/en-us/documentation/articles/app-insights-javascript/).
=> Add Application Insights analytics support

source/css/_schemes/Muse/_menu.styl
在站点配置文件中设置总计超过6个首页菜单项目（归档、标签、关于、搜索等），然后切换至移动/平板布局下，点击页面上方的汉堡菜单时，会无法遮挡文章标题内容而出现菜单文字混淆覆盖的问题，可以简单修复一下
=> fix Muse menu drop down layout

source/js/src/schemes/pisces.js
Use pisces scheme, when the first time open a page, if the browser window is less
than 991 px, and then adjust the browser window more than 991
px, the #sidebar margin-top error.
I add a media change event listener to fix it.
=> bugfix -- Pisces scheme sidebar positioning error

README.en.md
This PR updates the readme to use the same syntax as used in [`_config` example](https://github.com/iissnan/hexo-theme-next/blob/master/_config.yml#L247) for disqus integration.
=> corrected disqus example in readme

layout/_macro/post.swig, scripts/tags/button.js, source/css/_common/components/post/post-button.styl, source/css/_common/components/post/post.styl, source/css/_common/components/tags/full-image.styl, source/css/_schemes/Mist/_posts-expanded.styl, source/css/_schemes/Pisces/_full-image.styl, source/css/_schemes/Pisces/index.styl, source/css/_variables/Pisces.styl, source/css/_variables/base.styl
1. 	CSS: add custom `fi` vars.			a8db584
2. 	CSS: delete `_full-image.styl` file. (2)			c1e805c
3. 	CSS: remove `_full-image.styl` import. (3)			93d1ed7
4. 	CSS: add default `fi` vars. (4)			3de4ad3
5. 	CSS: add default `fi` vars. (5)			b9a42e3
Simply add variables in `source/css/_variables/custom.styl` like:
```
$full-image-width             = 100%;
$full-image-margin-horizontal = 0;
$full-image-margin-vertical   = 0;
```
where
- `$full-image-width` by default is `118%` for Pisces scheme.
- `$full-image-margin-horizontal` by default is `-9%` for Pisces scheme.
- `$full-image-margin-vertical` by default is `0` for Pisces scheme.
1. 	Create button.js			522ae9e
2.	CSS: add margin button style for Mist. (2)			361266f
3.	CSS: rename `post-more-link`. (3)			b0b9599
4.	CSS: rename file & add …
=> Fixes and enhancements. [6]

source/css/_schemes/Pisces/_menu.styl
Nav icon: To align the "site-nav-toggle" vertically in the center
原来不垂直居中，特别是有subtitle的时候。
移动端菜单导航按钮垂直居中显示
=> 让Pisces主题，移动端菜单导航按钮垂直居中显示

source/css/_common/components/post/post-button.styl
在[#1328](https://github.com/iissnan/hexo-theme-next/pull/1328)中，漏修改post-more-link选择器导致了这个问题
=> fix Issue #1360.

layout/_scripts/third-party/comments/youyan.swig
The current NexT theme loads a script unconditionally:
http://v2.uyan.cc/code/uyan.js?uid=
The reason is forgetting to check the value of theme.youyan_uid.
Fix the problem by putting statements in the condition for theme.youyan_uid.
=> third-party/uyan: disable uyan.js if uyan is off

_config.yml, layout/_scripts/third-party/analytics.swig, layout/_scripts/third-party/analytics/tencent-mta.swig
腾讯分析ta.qq.com已经基本没有在维护了。
现在都是在用http://mta.qq.com，不仅支持应用程序、HTML5还支持小程序
写了篇blog记录了下整个过程
http://blog.aleonchen.com/2017/02/03/MTA/
=> add Tencent MTA support (腾讯移动分析)

layout/_macro/sidebar.swig, layout/_scripts/third-party/analytics/vkontakte-api.swig
1. 	Fix `description` for `seo` option in #1311.  …			e6ff3bf
If `seo` is true main site description will be passed by `config.subtitle` option in main Hexo config.
But, there is duplicate of description by sidebar code (author & description).
So, we will separate main site description and author description and u may use `theme.signature` option for author description (signature).
In Next theme config:
``` yml
seo: true
```
In main Hexo config:
``` yml
title: 
subtitle:
description:
author:
signature: your Author signature here...
```
***
1. 	Fix `VK.Widgets: object #vk_like not found.`			aa4a1fb
`Uncaught Error: VK.Widgets: object #vk_like not found.` on homepage if `vkontakte_api.like` option is enabled.
=> Fixes and enhancements. [8]

layout/_scripts/third-party/analytics/google-analytics.swig
Fix Google Analytics can’t use
=> Fix Issues 1134

languages/default.yml, languages/en.yml, languages/fr-FR.yml, languages/ru.yml, languages/zh-Hans.yml, languages/zh-hk.yml, languages/zh-tw.yml, layout/_partials/search/localsearch.swig, source/css/_common/components/third-party/localsearch.styl, source/css/_common/scaffolding/helpers.styl
Tested on PC and mobile with all the  three schemes.
Before:
After:
mobile-no-keywords
mobile-with-keywords
pc-no-keywords
pc-no-result.png
pc-with-keywords
=> update local search style

source/js/src/utils.js
For example: if href is "https://example.com/test.png!/format/webp", the fancybox will not work well.
Fixed by specify type directly by adding classname "fancybox.image".
=> fixed: fancybox not work when can not figure out content type by href

_config.yml, layout/_macro/post-copyright.swig, layout/_macro/post.swig
```yml
post_copyright:
enable: true
license: CC BY-NC-SA 3.0 CN
license_url: http://creativecommons.org/licenses/by-nc-sa/3.0/cn/
```
=> feat: add the configure for declare copyright on posts

_config.yml, layout/_macro/post.swig, layout/_partials/comments.swig, layout/_scripts/third-party/comments.swig, layout/_scripts/third-party/comments/changyan.swig
add changyan comments, [see demo](http://www.zhaiqianfeng.com/2017/03/changyan-for-hexo-next-theme.html).
now duoshuo and youyan always go wrong. I add changyang to the theme,hope to be helpful.
=> add changyan comments

source/css/_common/components/highlight/highlight.styl, source/css/_common/components/post/post-expand.styl
When view `Code block` in mobile device frequently need to drag horizontal bar, consider it is not long enough, so make code block full-width in mobile.
=> Adjust code block display in mobile for better UX

source/css/_common/components/post/post-expand.styl
Code block behaves normal on desktop, here is a demo:
But when width <= 767px (e.g. on a mobile device), it will overflow screen like this (simulate in Chrome using iPhone 6 device model):
You can find line numbers overflow screen.
After fixed, it behaves normal again (simulate in Chrome using iPhone 6 device model):
=> fix: codeblock overflows screen when width <= 767px

layout/_third-party/comments/livere.swig
Since Disqus's settings change from `disqus_shortname` to `disqus.enable` and `disqus.shortname`, LiveRe's origin loading conditions fail.
LiveRe will be loaded without checking `page.comments`, I fix it too.
=> fix: LiveRe's loading conditions fail due to breaking changes of Disqus settings

_config.yml, layout/index.swig
=> add subtitle to home index

_config.yml, layout/_third-party/search/localsearch.swig, source/css/_common/components/third-party/localsearch.styl
Improvements:
- Let search input get focus automatically when search panel pops up
- Clean search input and search result when search panel closes
- When search panel pops up, click anywhere outside search panel can close it
- Sort result by hit count in article. Demo:
before:
after:
- Padding search icon and button. Comparison: 
before:
after:
- Support to highlight keywords in title. Demo:
- [**fix**] Let titles be shown with correct letter case instead of all lower case. Demo:
before:
after:
- [**fix**] When you input several keywords, all the keywords' result will be shown. Demo:
before:
after:
- Support to show first n highlighted results per article. Originally, search panel can only show first one result per article. Add a new configuration item `local_search.top_n_per_article` to …
=> enhancement: add several improvements to local search

_config.yml, layout/_third-party/search/localsearch.swig
Improvements:
- Add a new flag `local_search.trigger`. If set to `manual`, Search will be triggered by pressing enter key or search button (It's the default behavior); If set to `auto`,  Search will be triggered by changing input (It's the original default behavior, but suffer from lagging when containing many posts in site).
- Now results containing whole search text take precedence over other results, and articles containing more whole search texts take precedence over other articles. E.g., if you search "you can", results containing "you can" will be shown before results only containing "you" or "can".
=> enhancement: add 2 improvements to local search

layout/_third-party/search/localsearch.swig
add json option to local search.
TODO:
- search with tag and catalog
- doc update
=> json search engine support

source/lib/canvas-ribbon/canvas-ribbon.js
the code cause an exception.
```js
document.addEventListener("touchmove", function(e) {
e.preventDefault()
});
```
see that > [JS MDN](https://developer.mozilla.org/en-US/docs/Web/Events/touchmove)
=> fix ribbon cause scroll not working

source/lib/canvas-ribbon/canvas-ribbon.js
touch device process ->
touchstart -> touchmove -> touchend
so add some judgment to avoid changing in every touch screen
targetA = judgment
touchstart => targetA = true
touchmove => if the touch have move, it ain't click screen, so it ain't to change ribbon. targetA = true | false
touchend => if targetA = true will change ribbon, on the contrary not to do.
=> improve ribbon performance(touch device)

layout/_macro/post-collapse.swig, layout/_macro/post.swig, layout/category.swig, layout/page.swig, layout/tag.swig, source/css/_common/components/post/post-collapse.styl
=> Fixes titles & headers excess spaces.

layout/_third-party/analytics/tencent-mta.swig
Http url in https site will cause warning, but https url in http is ok.
=> Upgrade tencent-mta to 2.0.4 and using https

_config.yml
Menu links does not endwith slash, which cause github do 301 redirection. If use custom domain with https, it will cause twice 301 redirect, first redirected by github to http with slash, then redirect to https, which is not good for SEO.
Example : https://www.paddingleft.com/about
Add slash in menu config to reduce redirection.
=> fix github redirect for add slash issue

_config.yml
发现mathjax cdn访问很慢，查询后发现，根据官方公布，今年4月份`cdn.mathjax.org`已经关闭了: https://www.mathjax.org/cdn-shutting-down/
---
于是改用国内环境访问较快的: cdn.bootcss.com
=> fix: using bootcss cdn instead of mathjax official one because the official cdn has been closed

layout/_layout.swig
在使用Google Webmasters對網站做驗證時，
若Google Analytics追蹤碼不在head中會無法驗證，
將其移動到`<head></head>`中。
=> 將analytics放到<head>中使google webmasters可驗證。

source/lib/canvas-ribbon/canvas-ribbon.js
Bug fix: call `e()` function without set the `targetA = true`.
=> bug fix: Load the page for the first time, show ribbon

_config.yml, layout/_macro/sidebar.swig, source/css/_common/components/back-to-top-sidebar.styl, source/css/_common/components/back-to-top.styl, source/css/_common/components/sidebar/sidebar-dimmer.styl, source/css/_common/components/sidebar/sidebar-toggle.styl, source/css/_common/components/sidebar/sidebar.styl, source/css/_mixins/base.styl, source/js/src/motion.js
add a switch `onmobile` for `sidebar` in config.
If set, sidebar toggle will display on mobile and tablet view.
=> enable sidebar on mobile移动设备上开启侧栏

source/css/_common/components/sidebar/sidebar-blogroll.styl, source/css/_mixins/Pisces.styl, source/css/_schemes/Pisces/_sidebar.styl
In scheme **Pisces** and **Gemini** 
- The blogroll links should be in the center of the sidebar
- The default setting `links_layout: inline` doesn't work
In all scheme
- each blogroll link should have a max-width
=> Fix blogroll

source/css/_common/components/footer/footer.styl, source/css/_common/outline/outline.styl, source/css/_schemes/Pisces/_layout.styl
Like this image, if you add some custom sentences or just enable busuanzi like me, you'll find that footer height didn't increase as you want, and that would cause a bug when the inner HTML is too much, it will going into main part.
I fixed this problem, very simply, I read the css code and find NexT use a strange way to place the footer, that is let main use absolute position in the bottom and a big padding-bottom, then let the footer show above this padding-bottom, but the padding-bottom won't change automatically. I just removed those css, added a padding-top to footer,  then the footer will show after the main, and main's padding-bottom have nothing with footer, just the …
=> FIX: Better way to adjust footer position in Pisces.

_config.yml, layout/_partials/comments.swig, layout/_third-party/comments/index.swig, layout/_third-party/comments/valine.swig
Live demo [here](https://ioliu.cn/2017/add-valine-comments-to-your-blog/).
In Next `_config.yml`:
```yml
valine:
enable: false
appid:  # your leancloud application appid
appkey:  # your leancloud application appkey
```
=> Feature:Add Valine comment system support

_config.yml, layout/_layout.swig, layout/_partials/head.swig, layout/archive.swig, source/css/_common/components/pages/archive.styl, source/css/_common/components/post/post.styl, source/js/src/bootstrap.js, source/js/src/motion.js
Issue Number(s): #967.
1. Sidebar affix don't work globally (block extra was wrong usage).
2. Now `motion` option have more options:
* **Breaking changes**: rename `use_motion` to `motion` in main NexT config.
* Option to `async` loading. That's mean effects on logo, menu, post will load in same time if `true`; if `false` — this items will load after each other.
* Transition variants (see config comments).
* Motion effects now work for all pages (#967) and tags/category headers too.
```diff
-use_motion: true
+motion:
+  enable: true
+  async: false
+  transition:
+    # Transition variants:
+    # fadeIn | fadeOut | flipXIn | flipXOut | flipYIn | …
```
=> Refactor `motion` & sidebar affix global fix.

_config.yml, layout/_macro/sidebar.swig, layout/_partials/header.swig
1. Need to translate each custom menu item.
2. To menu and sidebar icons u must define icons in case-senstive at separated section.
Issue Number(s): #153, #360, #450, #737, #772, #810, #922, #1015, #1111, #1318, #1492, #1715, #1786, #1806.
1. No need to translate each custom menu item. If translate not found, Key (name) value will be shown as is (don't forget about UTF-8). Actially commit: 91eb2d272500993ccad1d15968a1beff9aaf3f03
2. Menu and sidebar icons now defined in same section where they keys specified.
In Next `_config.yml`:
```yml
menu:
home: / || home
#about: /about/ || user
#tags: /tags/ || tags
#categories: /categories/ || th
#archives: /archives/ || archive …
```
=> Menu & Sidebar icons in 1 line with Keys and Values of this icons.

_config.yml, layout/_macro/sidebar.swig
Default avatar loading if `avatar` option commented.
Issue Number(s): #1789.
Default avatar **not** loading if `avatar` option commented.
* Screens with this changes:
* Link to demo site with this changes: http://test.almostover.ru
```yml
#avatar: /images/avatar.gif
```
=> Commented `avatar` not visible in sidebar for now.

layout/_partials/share/jiathis.swig
`腾讯微薄` should be `腾讯微博`
https://github.com/iissnan/hexo-theme-next/issues/1833
=> tencent weibo typo #1833

_config.yml, scripts/merge-configs.js
Issue Number(s): #1860 
This PR adds a flag in the `_data/next.yml` configuration that allows the user to override the theme configuration. Useful if you don't want to inherit default set by the theme already.
```yml
override: true
```
=> Allow the user to override the whole configuration

languages/it.yml
Add Italian language support
```yml
...
```
=> Add Italian translation

_config.yml, source/css/_common/components/post/post-title.styl, source/css/_variables/base.styl
At the current status, generic font-sizes can't be configured by just editing the .yml configuration file. A fork of the theme is required, and an edit of some files is required.
The new approach goes towards an easier configuration of font-size throught the yml file:
- Add a possibility to configure them via the _config.yml file ( or data file )
- Reflect the configuration in base.styl
- Remove hardcoded font-sizes for headings inside post-title.styl
- Improve documentation around font customization inside the _config.yml file
See _config.yml inside this PR
=> Improve font configurations for global and headings

source/css/_common/components/pagination.styl
Line height was set with a fixed size. This would break easily if you increase/decrease the base font-size.
Removing the rule, allows the element to inherit the line-height, which is governed by the theme and auto-calculated. Making the overall pagination working just fine.
Nothing to be done.
=> Remove line-height declaration

_config.yml, layout/_partials/footer.swig
Signed-off-by: jokiestrunk <haocen.xu@gmail.com>
```yml
...
```
=> Options to better control footer.

source/lib/canvas-ribbon/canvas-ribbon.js
If use plugin [hexo-all-minifier](https://github.com/chenzhutian/hexo-all-minifier), will report an error:
```
ERROR Asset render failed: lib/canvas-ribbon/canvas-ribbon.js
```
So I upgrade this script file from https://github.com/zproo/canvas-ribbon.
Now error is not appear.
=> Fix canvas-ribbon error.

layout/_third-party/comments/gitment.swig
fix the bug of gitment, change `document.location.href` to `document.location.pathname`
```yml
...
```
=> fix #1943 fix the bug of gitment

_config.yml, layout/_macro/post.swig, layout/_partials/comments.swig, layout/_third-party/comments/valine.swig
```yml
-# more info please open https://github.com/xCss/Valine
+# more info please open https://valine.js.org
valine:
enable: false
appid:  # your leancloud application appid
appkey:  # your leancloud application appkey
notify: false # mail notifier , https://github.com/xCss/Valine/wiki
verify: false # Verification code
-  placeholder: Comment input placeholder
+  placeholder: Just go go # comment box placeholder
+  avatar: mm # gravatar style
+  guest_info: nick,mail,link # custom comment header
+  pageSize: …
```
=>  Fix: update valine comment system version and update configuration

source/css/_common/components/tags/full-image.styl
This bug comes from https://github.com/iissnan/hexo-theme-next/pull/1862. Now it should be give a bigger level.
=> Fix issue #2039.
