iissnan/hexo-theme-next

layout/_partials/header.swig

Fix the [issue 8](https://github.com/iissnan/hexo-theme-next/issues/8)

Fix the url_for function missing when render menu and feed urls.

---

languages/fr-FR.yml

Hello, i've translated your english config file to my native tongue.
Feel free to use it.
(Your template is really cool)

Add french translation

---

_config.yml
layout/_partials/head.swig

seo keywords update, post tags => post keywords

---

layout/page.swig

Bug: Wrong title in page category and tag

---

_config.yml
layout/_partials/footer.swig
source/css/_component/gallery.styl

之前的在ie上显示不正确，overflow:hidden不管用，去掉display:table后，图片会被裁切，不美观，感觉还是把所有图片显示出来好看一点，希望给予采纳。
新效果如 http://nullsheng.com/ 所示。

改变gallery显示方式

---

languages/de.yml

Created german translation for the 'Next' theme. Might be useful to someone.
(Maybe the available languages should also be mentioned in the README? There are quite a few by now)

Added German Translation

---

source/js/motion_global.js

I‘ve made some comment for detail.

fix sidebar repeatedly motion bug

---

README.md

wiki链接地址的修改

---

layout/_macro/sidebar.swig

Adding the following codes in the site's _config.yml file:
```
links_title: Links
links:
MacTalk: http://macshuo.com/
```

Adding feature: friendly links

---

layout/_layout.swig
layout/post.swig

让所有页面支持评论。关闭特定页面的评论可以在front-matter里增加`comments: false`

modified comment

---

source/js/hook-duoshuo.js

Bug:comments can not be display when admin_enable is false.#304

---

layout/_layout.swig
source/css/_common/_core/scaffolding.styl
source/css/_schemes/Mist/index.styl
source/css/_variables/base.styl
source/js/nav-toggle.js

紧凑版的主题，文章排版过于紧凑，没有「喘息的空间」。
将段落的间隔与行高做了一些调整，效果见下图：

CSS: update paragraph style

---

layout/_partials/head.swig

首先感谢作者的主题，个人的博客换上去之后变酷了很多。
作为国内没有谷歌的替代百度，且奇虎都有，没有理由会少，想要加上这部分在里面。

Add the baidu site vertification.

---

source/css/_custom/custom.styl
source/js/fancy-box.js

Add title to article and fancybox title;custum css on title

---

layout/_macro/post.swig
layout/_partials/head.swig
layout/_scripts/analytics.swig
layout/_scripts/analytics/facebook-sdk.swig

```yaml
facebook_sdk:
enable: true
app_id: <app_id>
fb_admin: <user_id>
like_button: true
webmaster: true
```

Support facebook SDK

---

_config.yml
languages/zh-Hans.yml
languages/zh-hk.yml
languages/zh-tw.yml
layout/_layout.swig
layout/_macro/post.swig
layout/_scripts/lean-analytics.swig

基于[leancloud](https://leancloud.cn/intro.html#/storage) 的Javascript实现的一个文章阅读量功能，能够统计每篇文章的阅读量(pv统计方式)。效果预览请移步：[夏末‘S NOTE](http://notes.xiamo.tk).

feature:notes and show number of visitors to each article

---

source/css/_common/_core/base.styl
source/css/_common/_core/scaffolding.styl

1、h2, h3, h4, h5, h6 margin值稍微小点可能会更好看
2、H标签行高调整
改前
改后

调整文章页面显示样式

---

layout/_macro/sidebar.swig

---
title: 
layout: post
toc_number: false
---
可以在 post 中单独配置是否显示 TOC 的标题序号

在 post 中也可以添加一个配置项 toc_number，这样就可以单独为 post 设置了。

---

source/js/hook-duoshuo.js

上次的PR被覆盖了
https://github.com/iissnan/hexo-theme-next/pull/433

同pull request #443

---

source/css/_common/_component/duoshuo.styl
source/css/_schemes/Mist/_posts-expanded.styl

I found a wrong word that cause "hexo-autoprefixer" breakdown.

Revised a wrong word. Made duoshuo style unified.

---

source/css/_common/_section/header.styl

issue #499 Fix menu align center on table

---

_config.yml

add commont for avatar

---

languages/default.yml
languages/en.yml
languages/fr-FR.yml

> Prepositions are only capitalized if they are used adjectivally or adverbially
So `of` should not be capitalized.

Fix Table of Contents type error

---

layout/_partials/head.swig

- fix undefined duoshuo_info.
- use `json_encode` for sidebar settings

Fix CONFIG

---

_config.yml
layout/_scripts/third-party/analytics.swig
layout/_scripts/third-party/analytics/tencent-analytics.swig

Google analytics 虽好，在大陆总有一层墙的问题。
百度统计虽然很多人用，但相信总有越来越多的人因为百度的持续性作死而放弃使用其全部产品。
所以希望加上对腾讯统计的支持，another choice :)

Add support for tencent analytics.

---

source/css/_schemes/Pisces/_sidebar.styl

fixed social link layout

---

layout/_macro/sidebar.swig

Save people with obsessive-compulsive disorder like me.

Hide categories or tags in sidebar if equal to 0.

---

source/css/_common/outline/outline.styl

fix pisces scheme layout on the left

fix pisces layout

---

layout/_partials/footer.swig

Fixed a history problem, icon-next-heart is useless and may interfere with other custom icons.

---

layout/_scripts/pages/post-details.swig
source/js/src/motion.js

修复了侧边栏不自动弹出的问题
modified:   layout/_scripts/pages/post-details.swig
modified:   source/js/src/motion.js

Fix Bug #614 #633

---

source/css/_common/components/header/menu.styl

Fix nav link center on mobile

---

layout/_scripts/pages/post-details.swig
source/css/_common/components/post/post-expand.styl
source/css/_schemes/Mist/_base.styl

- 修复在 Pisces 主题下错误弹出空白侧栏的 bug。
- 修复无序列表显示。

Fixes bugs

---

layout/_scripts/third-party/localsearch.swig
source/css/_common/components/third-party/localsearch.styl
source/css/_common/scaffolding/helpers.styl
source/css/_schemes/Mist/index.styl

Set ajax to async; fix a bug caused by 'substr'; Some UI improvement especially on mobile view....

local search improvement

---

layout/_partials/search/localsearch.swig
layout/_scripts/third-party/localsearch.swig
source/css/_common/components/third-party/localsearch.styl
source/css/_common/scaffolding/helpers.styl

remove search form completely

---

_config.yml
layout/_layout.swig
layout/_scripts/baidu-push.swig

自动将页面推送给百度从而大幅提升百度收录速度，同时有助于SEO
百度相关功能介绍
http://zhanzhang.baidu.com/college/courseinfo?id=267&page=2#h2_article_title19

Add baidu push functionality which is helpful for SEO

---

layout/_macro/reward.swig

Fix bug for wechat and alipay reward #687  Issue #777

Fixed reward bug

---

layout/_layout.swig
layout/_partials/footer.swig
layout/_scripts/third-party/analytics/busuanzi-counter.swig
source/css/_common/components/footer/footer.styl
source/css/_common/components/third-party/busuanzi-counter.styl
source/css/_common/components/third-party/third-party.styl

and fix alignment problems in footer

busuanzi: move to 'third-party' directory

---

layout/_macro/reward.swig
source/css/_common/components/post/post-reward.styl
source/css/_common/components/post/post.styl

将reward的样式抽取出来，并移植了我博客上的效果，望采纳，演示：http://zhuweisheng.com.cn/technology/spider/

reward style

---

layout/_scripts/third-party/lean-analytics.swig

Set ACL for new LeanCloud Counter object

---

_config.yml
layout/_partials/head.swig

Let this theme more easy setting canonical for SEO blog.

Add canonical setting.

---

layout/_scripts/third-party/analytics/cnzz-analytics.swig

fix_cnzz_https

---

layout/_components/algolia-search/assets.swig

fix algolia_instant_css href path

---

languages/pt-BR.yml

Great theme.
I intend to polularizá it here in Brazil
Thank's

Add translate to pt-BR

---

layout/_scripts/third-party/comments/duoshuo.swig

修复多说duoshuo_info.admin_enable未开启时，duoshuo_info.ua_enable不起作用。

fix_duoshuo_ua

---

_config.yml
layout/_macro/post.swig
layout/_partials/comments.swig

Add two config settings about fb comments plugin, **width** and **scheme**.

Update fb comments plugin

---

languages/ko.yml

Hi! Thank you for the wonderful theme. I added new language file in Korean.

Add languages/ko.yml (korean version)

---

source/css/_schemes/Muse/_layout.styl

fix embed content margin in Muse schema

[add] embed tag style

---

source/css/_common/components/highlight/highlight.styl

For support diff highlight style

---

layout/_layout.swig
layout/_macro/post.swig
layout/_partials/head.swig
scripts/tags/full-image.js

1. To test structured data see 
[Google Structured Data Tool](https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fnotes.iissnan.com). 
2. To test W3C syntax see [W3 Html Checker](https://validator.w3.org/nu/?doc=http%3A%2F%2Fnotes.iissnan.com%2F).
3. To see all changes and results see [that article](https://almostover.ru/2016-08/schema-org-microdata-for-structured-data/).
After all fixes and improvements i have [this](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Falmostover.ru) and [this](https://validator.w3.org/nu/?doc=https%3A%2F%2Falmostover.ru) result.

Fixes of Schema.org and Microformats data.

---

layout/_scripts/third-party/comments/disqus.swig

Fix unused Disqus variables.

---

_config.yml

modify theme.vendors._internal from vendors to lib in _config.yml.

modify theme.vendors._internal from vendors to lib

---

_config.yml
layout/_partials/footer.swig

using heart is looks like a 娘炮, sorry.
I think user should decide which icon to use.

add config for diy icon between year and author @footer place

---

layout/_scripts/third-party/analytics/baidu-analytics.swig

modify baidu analytics http => https

---

layout/_partials/header.swig

相关 Issue：https://github.com/iissnan/hexo-theme-next/issues/1176

Bug fix: enable search popup when algolia search is enabled

---

README.en.md

I fixed minor typo in english documentation.

Fix minor typo in README.en.md

---

_config.yml
layout/_partials/comments.swig
layout/_scripts/third-party/comments.swig
layout/_scripts/third-party/comments/livere.swig

for issue #1396
add LiveRe comments for next themes
添加来必力评论支持
for more detail, please read my blog.
更多细节请访问我的博客 [https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html](https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html)

Add comment LiveRe

---

languages/zh-Hans.yml

同步default.yml

---

languages/default.yml
languages/en.yml
languages/fr-FR.yml
languages/zh-Hans.yml
languages/zh-hk.yml
languages/zh-tw.yml

remove duplicate key in Simplified Chinese (sorry for my mistake)
minor updates & fixes

fixed: Simplified Chinese translation (IMPORTANT)

---

layout/_partials/header.swig
source/css/_schemes/Pisces/_brand.styl
source/css/_schemes/Pisces/_menu.styl

Add site brand wrapper

---

source/css/_common/components/third-party/busuanzi-counter.styl
source/css/_schemes/Pisces/_layout.styl

fixed: footer layout

---

source/css/_common/components/sidebar/sidebar-toggle.styl

Fixes for Muse and Mist schemes for #1438.

Some small fixes.

---

_config.yml
layout/_scripts/third-party/localsearch.swig

fixed: local search overlay layout

---

source/css/_common/components/back-to-top.styl
source/css/_common/components/sidebar/sidebar-toggle.styl

Last fixes for Muse and Mist schemes for #1438.

Last fix of sidebar toggle & b2t width style.

---

scripts/tags/exturl.js

Rollback to 'hexo-util'.

---

_config.yml

增加 three_waves  配置文件

---

source/css/_schemes/Pisces/_layout.styl

fix footer layout

---

source/js/src/utils.js

utils.js脚本错误导致主题页面无法加载，已提交pull request

Fix utils.js error

---

layout/_third-party/search/localsearch.swig

Compatible with old browser

---

package.json

version error.

---

source/js/src/motion.js

Detecting touch trace to trigger sidebar toggle

Little trick enabling sidebar closing through swiping

---

layout/_third-party/analytics/lean-analytics.swig

Reverts iissnan/hexo-theme-next#1724
Fix bug #1760.

Revert "修正 leancloud 计数不能正常显示问题"

---

_config.yml
layout/_partials/head.swig

Add support for Bing webmaster tools.
Just simple improvement.

Add: Bing verification

---

source/css/_common/components/sidebar/sidebar-author-links.styl
source/css/_schemes/Pisces/_sidebar.styl

> When I open my homepage, I can see some links on the right side. And when open the right side bar, this bug will disappear.
Issue Number(s): #1840.
Pull request: #1697 PART 3.

FIX: move `flex` style from global sidebar style to Pisces and Gemini schemes only.

---

languages/de.yml
languages/default.yml
languages/en.yml
languages/fr-FR.yml
languages/id.yml
languages/ja.yml
languages/ko.yml
languages/pt-BR.yml
languages/pt.yml
languages/ru.yml
languages/zh-Hans.yml
languages/zh-hk.yml
languages/zh-tw.yml
layout/_macro/reward.swig
source/css/_common/components/post/post-reward.styl

1. Add `Donate` internationalization (only finished Chinese version).
2. Fix `Donate` Button was ellipse on Safari.

Add Donate internationalization && Fix Donate Button Style

---

languages/zh-hk.yml
languages/zh-tw.yml

Sorry, I make a mistake.
Two space should be used in file.

FIX:language space typo

---

source/css/_common/components/post/post-expand.styl

Add 25px margin-bottom space from picture to text.
Make sure also the rule wins on top of the others ( before it was overridden anyway )
Comes for free.

Fix fancybox style

---

source/css/_common/components/post/post.styl

As the image pushes down to 25px, the caption text is too distant from the picture now, missing the visual meaning of it.
We lift it up ( if present ) at least 20px. Preserving a space of 5px between the picture and the caption text.
```yml
...
```

Fix caption position

---

source/css/_common/outline/outline.styl
source/css/_schemes/Pisces/_layout.styl

Reverts iissnan/hexo-theme-next#1807

Revert "FIX: Better way to adjust footer position in Pisces."

---

source/css/_schemes/Mist/_posts-expanded.styl

The font-size on mobile feels unnatural for posts, when using Mist.
Now it looks much better. Titles are bigger than the normal post font.
Nothing to be done.

Fix Mist font-size for Posts on mobile

---

source/css/_schemes/Mist/_posts-expanded.styl

Issue Number(s): #1889
The font-size is now smaller only for mobile devices.

Fix font-size only for mobile

---

layout/_third-party/comments/valine.swig

* Screens with this changes: 
* Link to demo site with this changes: [Demo](https://valine.js.org)
```yml
...
```

Fix:update valine comment system version

---

languages/nl-NL.yml

This PR adds a Dutch translation

🌐 Add Dutch translation

---

source/css/_schemes/Muse/_menu.styl

Fixed issue #1946.

---

_config.yml

Adjust gitment comments

---

README.cn.md

fix a small translate bug

---

languages/vi.yml

I just created Vietnamese Language file. Please accept.
Thanks.

Add Vietnamese Language

---

source/css/_common/components/sidebar/sidebar-toc.styl
source/js/src/utils.js

Fix issue #1923.

---

README.cn.md
README.md

Only Add Recommend Markdown Editor: HexoEditor

Only Add Recommend Markdown Editor: HexoEditor
